### ISSUE TITLE
Redirection issue

### ISSUE THREAD

**Issue by Magisterivm** [Continuation-of-Ashford/ashford-docs#1]
[Mechanics](https://github.com/Continuation-of-Ashford/ashford-docs/blob/main/mechanics.md#skillproficiency) under **Skill/Proficiency** does not refer to the actual [downtime](https://github.com/Continuation-of-Ashford/ashford-docs/blob/main/Downtimes.mdl) page.

**Comment by begna112** [comment]
This was resolved at some point.
